FROM centos:centos7
MAINTAINER Takashi Yoshioka
ENV container dcker
ENV http_proxy http://proxy.your.site.co.jp:8080
ENV https_proxy http://proxy.you.iste.co.jp:8080
RUN yum swap -y fakesystemd systemd
RUN yum install -y initscripts
RUN yum install -y httpd
RUN echo "Hello Apache." > /var/www/html/index.html
RUN systemctl enable httpd
EXPOSE 80


